import turtle

#declaration de variable appeler zh
zh=turtle.Turtle()

#fonction pour creer une case
def case(N):
        #la dimensionnement des different est rendu possible par l'utilisation du theorele d'al  kasi
        zh.left(180)
        zh.left(30)
        zh.forward(70)
        zh.right(180)
        zh.right(30)
        zh.forward(121)
        zh.right(180)
        zh.right(30)
        zh.forward(70)
        zh.right(60)
        zh.left(90)
        zh.left(30)
        zh.forward(70)
        zh.left(60)
        '''zh.forward(40)
        zh.left(90)
        zh.forward(121)
        zh.left(90)
        zh.forward(40)'''
        #construction du mur en bas du case
def mur(r):
        zh.forward(40)
        zh.left(90)
        zh.forward(121)
        zh.left(90)
        zh.forward(40)
        #construction du toie
def toile(t):


        zh.left(0)
        zh.forward(150)
        case(5)
        mur(5)
        zh.left(60)
        zh.forward(70)
        zh.left(30)
        zh.forward(288)
        zh.left(180)
        case(5)
        mur(5)
        zh.left(180)
        zh.left(90)
        zh.forward(167)


#fonction d'un rectangle
def Dcarre(D):
        for j in range(2):
                zh.forward(30)
                zh.right(90)
                zh.forward(8)
                zh.right(90)
#fonction pour les petites rectangle en bas de la case
def rect(R):
        zh.color("black", "gray")#couleur de peint et de remplissage
        zh.begin_fill()# debut remplissage
        for k in range(2):
                zh.forward(70)
                zh.left(90)
                zh.forward(230)
                zh.left(90)
        zh.end_fill()# debut remplissage
def car1(car):
        for l in range(4):
                        zh.forward(27)
                        zh.left(90)
#foncton pour les double rectangle
def car2(car2):
        car1(5)
        zh.left(90)
        zh.forward(27)
        car1(5)
def car4(car4):
        zh.color("black", "white")#couleur de peint et de remplissage
        zh.begin_fill()
        car2(5)
        zh.left(90)
        zh.forward(27)
        zh.left(90)
        car2(5)
        zh.end_fill()# debut remplissage
#fonction des rectangle a l'interieur du batiment
def rect1(rect):
        zh.color("black", "white")#couleur de peint et de remplissage
        zh.begin_fill()
        for a in range(2):
              zh.forward(27)
              zh.left(90)
              zh.forward(54)
              zh.left(90)
        zh.end_fill()# debut remplissage
def rect2(rect2):
        zh.color("black", "white")#couleur de peint et de remplissage
        zh.begin_fill()
        rect1(5)
        zh.left(90)
        zh.forward(54)
        zh.right(90)
        rect1(5)
        zh.end_fill()# debut remplissage
#fontion des 4 carré groupé a l'interieur des rectangle
def rect4(rect4):

        rect2(5)
        zh.left(90)
        zh.forward(54)
        zh.left(90)
        rect2(5)
        zh.end_fill()# debut remplissage
#fonction des 4 rectangle en bas à l'interieur du rectangle
def rect5(rect5):
        zh.color("black", "white")#couleur de peint et de remplissage
        zh.begin_fill()
        for a in range(2):
              zh.forward(37)
              zh.right(90)
              zh.forward(116)
              zh.right(90)
              zh.end_fill()# debut remplissage

def rect6(rec2t):
        zh.color("black", "light gray")#couleur de peint et de remplissage
        zh.begin_fill()
        for c in range(2):
                zh.forward(70)
                zh.right(90)
                zh.forward(180)
                zh.right(90)
        zh.end_fill()# debut remplissage
#fonction du rectangle en chevalé en haut entre les deux groupement des rectangle
def rect11(rect11):
        for a in range(2):
                zh.forward(20)
                zh.left(90)
                zh.forward(40)
                zh.left(90)


def rect22(rect22):
        zh.color("black", "white")#couleur de peint et de remplissage
        zh.begin_fill()
        rect11(5)
        zh.left(90)
        zh.forward(40)
        zh.left(90)
        rect11(5)
        zh.end_fill()# debut remplissage# debut remplissage
#derniere rectangle de 2 case
def Drect1(rect):
        for a in range(2):
              zh.forward(23)
              zh.left(90)
              zh.forward(35)
              zh.left(90)
def Drect2(rect2):
        Drect1(5)
        zh.left(90)
        zh.forward(35)
        zh.right(90)
        Drect1(5)
#fonction du rectangle de 4 case en bas enchevalé entre les groupement des rectangle
def Drect4(rect4):
        zh.color("black", "white")#couleur de peint et de remplissage
        zh.begin_fill()
        Drect2(5)
        zh.left(90)
        zh.forward(35)
        zh.left(90)
        Drect2(5)
        zh.end_fill()# debut remplissage
#fonction du sphere
def sphere(sp):
        zh.color("black", "black")#couleur de peint et de remplissage
        zh.begin_fill()
        zh.circle(9)
        zh.end_fill()# debut remplissage
#fonction d'une marche d'escallier
def scal0(m):
        for o in range(2):

              zh.forward(6)
              zh.right(90)
              zh.forward(m)
              zh.right(90)
#les manipulation et ajustement

toile(5)
zh.right(90)
zh.forward(40)
zh.right(90)
zh.forward(167)
zh.forward(103)
zh.right(90)
Dcarre(5)
zh.right(90)
zh.forward(8)
zh.left(90)
Dcarre(5)
zh.right(90)
zh.forward(24)
zh.left(90)
Dcarre(5)
zh.right(90)
zh.forward(8)
zh.left(90)
Dcarre(5)
zh.right(90)
zh.forward(24)
zh.left(90)
Dcarre(5)
zh.right(90)
zh.forward(8)
zh.left(90)
Dcarre(5)
zh.right(90)
zh.forward(48)
zh.left(90)
Dcarre(5)
zh.right(90)
zh.forward(8)
zh.left(90)
Dcarre(5)
zh.right(90)
zh.forward(24)
zh.left(90)
Dcarre(5)
zh.right(90)
zh.forward(8)
zh.left(90)
Dcarre(5)
zh.right(90)
zh.forward(16)
zh.left(90)
Dcarre(5)
zh.right(90)
zh.forward(8)
zh.left(90)
Dcarre(5)
zh.right(90)
zh.forward(16)
zh.left(90)
Dcarre(5)
zh.right(90)
zh.forward(8)
zh.left(90)
Dcarre(5)
zh.right(90)
zh.forward(24)
zh.left(90)
Dcarre(5)
zh.right(90)
zh.forward(8)
zh.left(90)
Dcarre(5)
zh.right(90)
zh.forward(47)
zh.left(90)
Dcarre(5)
zh.right(90)
zh.forward(8)
zh.left(90)
Dcarre(5)
zh.right(90)
zh.forward(24)
zh.left(90)
Dcarre(5)
zh.right(90)
zh.forward(8)
zh.left(90)
Dcarre(5)
zh.right(90)
zh.forward(24)
zh.left(90)
Dcarre(5)
zh.right(90)
zh.forward(8)
zh.left(90)
Dcarre(5)
zh.right(90)
zh.forward(150)
zh.right(120)
zh.forward(40)
zh.right(60)
zh.forward(600)
zh.right(60)
zh.forward(40)
zh.right(120)
zh.forward(150)
zh.left(180)
zh.forward(150)
zh.left(120)
zh.forward(40)
zh.right(30)
zh.forward(250)
zh.left(90)
zh.forward(600)
zh.left(90)
zh.forward(250)
zh.penup()
zh.left(180)
zh.forward(5)
zh.right(90)
zh.forward(5)
zh.pendown()
rect(5)
zh.penup()
zh.forward(86)
zh.pendown()
rect(5)
zh.penup()
zh.forward(86)
zh.pendown()
rect(5)
zh.penup()
zh.forward(178)
zh.pendown()
rect(5)
zh.penup()
zh.forward(86)
zh.pendown()
rect(5)
zh.penup()
zh.forward(86)
zh.pendown()
rect(5)
zh.penup()
zh.left(90)
zh.forward(8)
zh.right(90)
zh.forward(36)
zh.pendown()
car4(5)
zh.penup()
zh.left(180)
zh.forward(85)
zh.left(90)
zh.forward(28)
zh.left(90)
zh.pendown()
car4(5)
zh.penup()
zh.left(180)
zh.forward(85)
zh.left(90)
zh.forward(28)
zh.left(90)
zh.pendown()
car4(5)
zh.penup()
zh.left(180)
zh.forward(180)
zh.left(90)
zh.forward(28)
zh.left(90)
zh.pendown()
car4(5)
zh.penup()
zh.left(180)
zh.forward(85)
zh.left(90)
zh.forward(28)
zh.left(90)
zh.pendown()
car4(5)
zh.penup()
zh.left(180)
zh.forward(87)
zh.left(90)
zh.forward(28)
zh.left(90)
zh.pendown()
car4(5)
zh.penup()
zh.left(90)
zh.forward(88)
zh.right(90)
zh.pendown()
rect4(5)
zh.penup()
zh.left(90)
zh.forward(54)
zh.left(90)
zh.forward(85)
zh.pendown()
rect4(5)
zh.penup()
zh.left(90)
zh.forward(54)
zh.left(90)
zh.forward(85)
zh.pendown()
rect4(5)
zh.penup()
zh.left(90)
zh.forward(54)
zh.left(90)
zh.forward(180)
zh.pendown()
rect4(5)
zh.penup()
zh.left(90)
zh.forward(54)
zh.left(90)
zh.forward(85)
zh.pendown()
rect4(5)
zh.penup()
zh.left(90)
zh.forward(54)
zh.left(90)
zh.forward(85)
zh.pendown()
rect4(5)
zh.penup()
zh.forward(200)
zh.left(90)
zh.forward(175)

zh.pendown()
rect5(5)

zh.penup()
zh.right(90)
zh.forward(25)
zh.pendown()
rect6(5)
zh.right(180)
zh.forward(8)
zh.left(90)
zh.forward(180)
zh.right(180)
zh.forward(180)
zh.left(90)
zh.forward(8)
zh.left(90)
zh.forward(180)
zh.left(180)
zh.forward(180)
zh.right(90)
zh.forward(100)
zh.right(90)
zh.forward(180)
zh.left(180)
zh.forward(180)
zh.left(90)
zh.forward(6)
zh.left(90)
zh.forward(180)
zh.penup()
zh.left(180)
zh.forward(180)
zh.left(90)
zh.forward(45)
zh.left(90)
zh.forward(14)
zh.right(90)


zh.pendown()
rect22(5)
zh.penup()
zh.right(90)
zh.forward(56)
zh.right(90)
zh.pendown()
Drect4(5)
zh.penup()
zh.left(90)
zh.forward(35)
zh.right(90)
zh.forward(23)
zh.left(90)
zh.pendown()
zh.circle(23,180)
zh.penup()
zh.left(90)
zh.forward(32)
zh.left(90)
zh.forward(40)
zh.pendown()
sphere(5)
zh.penup()
zh.left(90)
zh.forward(40)
zh.left(90)
zh.forward(41)
zh.left(90)
zh.forward(53)
zh.right(90)
zh.forward(69)
zh.right(90)
zh.forward(71)
zh.left(180)


zh.pendown()
zh.forward(100)
zh.right(90)
scal0(100)
zh.left(90)
zh.left(180)
zh.forward(6)
zh.left(90)
zh.left(90)
scal0(55)
zh.left(180)
zh.forward(94)
zh.left(90)
zh.forward(55)
zh.left(90)
zh.forward(7)
zh.left(90)
zh.forward(55)
zh.right(90)
zh.forward(70)
zh.right(90)
zh.forward(6)

scal0(54)
#1#
zh.forward(6)
zh.left(90)
zh.forward(2)
zh.right(90)
scal0(58)
#2#
zh.forward(6)
zh.left(90)
zh.forward(2)
zh.right(90)
scal0(62)
#3#
zh.forward(6)
zh.left(90)
zh.forward(2)
zh.right(90)
scal0(66)
#4#
zh.forward(6)
zh.left(90)
zh.forward(2)
zh.right(90)
scal0(70)
#5#

zh.forward(6)
zh.left(90)
zh.forward(2)
zh.right(90)
scal0(74)

zh.forward(6)
zh.left(90)
zh.forward(2)
zh.right(90)
scal0(78)
zh.forward(6)
zh.left(90)
zh.forward(2)
zh.right(90)
scal0(82)
zh.forward(7)
zh.left(90)
zh.penup()
zh.forward(260)
zh.pendown()
zh.left(180)
zh.forward(600)


turtle.done()